### ISSUE TITLE
Will it unbindService twice?

### ISSUE THREAD

**Issue by luofan-creative** [evant/JobSchedulerCompat#17]
java.lang.IllegalArgumentException: Service not registered: me.tatarka.support.internal.job.a@42778390
at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:922)
at android.app.ContextImpl.unbindService(ContextImpl.java:1740)
at android.content.ContextWrapper.unbindService(ContextWrapper.java:536)
at me.tatarka.support.internal.job.JobSchedulerService.a(JobSchedulerService.java:212)
at me.tatarka.support.internal.job.JobSchedulerService.a(JobSchedulerService.java:29)
at me.tatarka.support.internal.job.a$1.jobFinished(JobSchedulerService.java:123)
at me.tatarka.support.job.d.handleMessage(JobService.java:122)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5426)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
at dalvik.system.NativeStart.main(Native Method)

**Comment by luofan-creative** [comment]
At JobSchedulerService:
private void finishJob(int jobId, JobServiceConnection connection) {
        if (runningJobs.get(jobId) != null) {
            unbindService(connection);
        }
        runningJobs.remove(jobId);
        JobStore jobStore = JobStore.initAndGet(this);
        synchronized (jobStore) {
            jobStore.remove(connection.job);
        }
    }

--------
Maybe it happen when unbindService cost more time,and then another finishJob call,
I think calling runningJobs.remove() first will be better.
