### ISSUE TITLE
Service not registered

### ISSUE THREAD

**Issue by luofan-creative** [evant/JobSchedulerCompat#18]
java.lang.IllegalArgumentException: Service not registered: me.tatarka.support.internal.job.a@42778390
at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:922)
at android.app.ContextImpl.unbindService(ContextImpl.java:1740)
at android.content.ContextWrapper.unbindService(ContextWrapper.java:536)
at me.tatarka.support.internal.job.JobSchedulerService.a(JobSchedulerService.java:212)
at me.tatarka.support.internal.job.JobSchedulerService.a(JobSchedulerService.java:29)
at me.tatarka.support.internal.job.a$1.jobFinished(JobSchedulerService.java:123)
at me.tatarka.support.job.d.handleMessage(JobService.java:122)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5426)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
at dalvik.system.NativeStart.main(Native Method)

**Comment by evant** [comment]
Can I get more detail on what you are trying to do/when you got the exception?

**Comment by arifnadeem7** [comment]
I encountered this issue 2 times today, I cannot figure out why, I am registering my service in Manifest.

It crashes on this line me.tatarka.support.internal.job.JobSchedulerService.finishJob (SourceFile:212)

Any suggestions on how to fix this problem?

**Comment by EddieRingle** [comment]
FWIW one of my coworkers is seeing this on his OnePlus One running 4.4 on an app we're working on, but I've yet to see it anywhere else (like a Galaxy Nexus running 4.3). It's rendered the app unusable for him, apparently. Uninstalling and reinstalling and device reboots don't help, either. Is it possibly a KitKat-specific issue or could it even be related to CyanogenMod (since it's only appearing on the OnePlus thus far)?

**Comment by mhajimiri** [comment]
I had the same issue solved by the solution given at issue #28 .
