### ISSUE TITLE
Exception JobSchedulerService has leaked ServiceConnection 

### ISSUE THREAD

**Issue by chrysimo** [evant/JobSchedulerCompat#25]
I encountered this issue 2 times today. Is anyone having this issue?

05-01 21:13:47.653: E/ActivityThread(11140): android.app.ServiceConnectionLeaked: Service me.tatarka.support.internal.job.JobSchedulerService has leaked ServiceConnection me.tatarka.support.internal.job.JobSchedulerService$JobServiceConnection@430e3130 that was originally bound here
05-01 21:13:47.653: E/ActivityThread(11140): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:988)
05-01 21:13:47.653: E/ActivityThread(11140): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:882)
05-01 21:13:47.653: E/ActivityThread(11140): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1912)
05-01 21:13:47.653: E/ActivityThread(11140): 	at android.app.ContextImpl.bindService(ContextImpl.java:1895)
05-01 21:13:47.653: E/ActivityThread(11140): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:529)
05-01 21:13:47.653: E/ActivityThread(11140): 	at me.tatarka.support.internal.job.JobSchedulerService.handleStartJob(JobSchedulerService.java:82)
05-01 21:13:47.653: E/ActivityThread(11140): 	at me.tatarka.support.internal.job.JobSchedulerService.access$0(JobSchedulerService.java:55)
05-01 21:13:47.653: E/ActivityThread(11140): 	at me.tatarka.support.internal.job.JobSchedulerService$1.handleMessage(JobSchedulerService.java:310)
05-01 21:13:47.653: E/ActivityThread(11140): 	at me.tatarka.support.internal.job.JobSchedulerService.onStartCommand(JobSchedulerService.java:46)
05-01 21:13:47.653: E/ActivityThread(11140): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2860)
05-01 21:13:47.653: E/ActivityThread(11140): 	at android.app.ActivityThread.access$2200(ActivityThread.java:161)
05-01 21:13:47.653: E/ActivityThread(11140): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
05-01 21:13:47.653: E/ActivityThread(11140): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-01 21:13:47.653: E/ActivityThread(11140): 	at android.os.Looper.loop(Looper.java:157)
05-01 21:13:47.653: E/ActivityThread(11140): 	at android.app.ActivityThread.main(ActivityThread.java:5356)
05-01 21:13:47.653: E/ActivityThread(11140): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-01 21:13:47.653: E/ActivityThread(11140): 	at java.lang.reflect.Method.invoke(Method.java:515)
05-01 21:13:47.653: E/ActivityThread(11140): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
05-01 21:13:47.653: E/ActivityThread(11140): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
05-01 21:13:47.653: E/ActivityThread(11140): 	at dalvik.system.NativeStart.main(Native Method)
05-01 21:13:47.673: D/AndroidRuntime(11140): Shutting down VM
05-01 21:13:47.673: W/dalvikvm(11140): threadid=1: thread exiting with uncaught exception (group=0x41831da0)
05-01 21:13:47.673: E/AndroidRuntime(11140): FATAL EXCEPTION: main
05-01 21:13:47.673: E/AndroidRuntime(11140): Process: com.example.mobile.ui, PID: 11140
05-01 21:13:47.673: E/AndroidRuntime(11140): java.lang.IllegalArgumentException: Service not registered: me.tatarka.support.internal.job.JobSchedulerService$JobServiceConnection@42f60160
05-01 21:13:47.673: E/AndroidRuntime(11140): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:940)
05-01 21:13:47.673: E/AndroidRuntime(11140): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1946)
05-01 21:13:47.673: E/AndroidRuntime(11140): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:541)
05-01 21:13:47.673: E/AndroidRuntime(11140): 	at me.tatarka.support.internal.job.JobSchedulerService.finishJob(JobSchedulerService.java:212)
05-01 21:13:47.673: E/AndroidRuntime(11140): 	at me.tatarka.support.internal.job.JobSchedulerService.access$4(JobSchedulerService.java:210)
05-01 21:13:47.673: E/AndroidRuntime(11140): 	at me.tatarka.support.internal.job.JobSchedulerService$JobServiceConnection$1.jobFinished(JobSchedulerService.java:123)
05-01 21:13:47.673: E/AndroidRuntime(11140): 	at me.tatarka.support.job.JobService$JobHandler.handleMessage(JobService.java:122)
05-01 21:13:47.673: E/AndroidRuntime(11140): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-01 21:13:47.673: E/AndroidRuntime(11140): 	at android.os.Looper.loop(Looper.java:157)
05-01 21:13:47.673: E/AndroidRuntime(11140): 	at android.app.ActivityThread.main(ActivityThread.java:5356)
05-01 21:13:47.673: E/AndroidRuntime(11140): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-01 21:13:47.673: E/AndroidRuntime(11140): 	at java.lang.reflect.Method.invoke(Method.java:515)
05-01 21:13:47.673: E/AndroidRuntime(11140): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
05-01 21:13:47.673: E/AndroidRuntime(11140): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
05-01 21:13:47.673: E/AndroidRuntime(11140): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by mhajimiri** [comment]
I had the same issue solved by the solution given at issue #28 .
