### ISSUE TITLE
java.lang.IllegalArgumentException: Service not registered

### ISSUE THREAD

**Issue by zishell** [evant/JobSchedulerCompat#30]
test your sample with android 4.4.2 , this is the log:

java.lang.IllegalArgumentException: Service not registered: me.tatarka.support.internal.job.JobSchedulerService$JobServiceConnection@42055c48
            at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:961)
            at android.app.ContextImpl.unbindService(ContextImpl.java:1690)
            at android.content.ContextWrapper.unbindService(ContextWrapper.java:529)
            at me.tatarka.support.internal.job.JobSchedulerService.finishJob(JobSchedulerService.java:212)
            at me.tatarka.support.internal.job.JobSchedulerService.access$000(JobSchedulerService.java:29)
            at me.tatarka.support.internal.job.JobSchedulerService$JobServiceConnection$1.acknowledgeStopMessage(JobSchedulerService.java:143)
            at me.tatarka.support.job.JobService$JobHandler.ackStopMessage(JobService.java:158)
            at me.tatarka.support.job.JobService$JobHandler.handleMessage(JobService.java:111)
            at android.os.Handler.dispatchMessage(Handler.java:110)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5292)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mhajimiri** [comment]
"Service not registered" problem had occured in my project as same as your experience. I changed jobscheduler source code as I mentioned in issue #28 and finaly the problem solved forever.
