### ISSUE TITLE
android.app.ServiceConnectionLeaked

### ISSUE THREAD

**Issue by zishell** [evant/JobSchedulerCompat#31]
test sample with android 4.4.2 , this is the log :

E/ActivityThread﹕ Service me.tatarka.support.internal.job.JobSchedulerService has leaked ServiceConnection me.tatarka.support.internal.job.JobSchedulerService$JobServiceConnection@41d7c648 that was originally bound here
    android.app.ServiceConnectionLeaked: Service me.tatarka.support.internal.job.JobSchedulerService has leaked ServiceConnection me.tatarka.support.internal.job.JobSchedulerService$JobServiceConnection@41d7c648 that was originally bound here
            at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1009)
            at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:903)
            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1656)
            at android.app.ContextImpl.bindService(ContextImpl.java:1639)
            at android.content.ContextWrapper.bindService(ContextWrapper.java:517)
            at me.tatarka.support.internal.job.JobSchedulerService.handleStartJob(JobSchedulerService.java:82)
            at me.tatarka.support.internal.job.JobSchedulerService.access$400(JobSchedulerService.java:29)
            at me.tatarka.support.internal.job.JobSchedulerService$1.handleMessage(JobSchedulerService.java:310)
            at me.tatarka.support.internal.job.JobSchedulerService.onStartCommand(JobSchedulerService.java:46)
            at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2868)
            at android.app.ActivityThread.access$2100(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1418)
            at android.os.Handler.dispatchMessage(Handler.java:110)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5292)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mhajimiri** [comment]
"ServiceConnectionLeaked" is occured because of the same conditions as I explained in issue #30 .
