### ISSUE TITLE
ClassCastException proguard only on 5.0 Nexus 7

### ISSUE THREAD

**Issue by tajchert** [evant/JobSchedulerCompat#33]
Error:

``` java
java.lang.RuntimeException: java.lang.ClassCastException: android.app.job.IJobCallback$Stub$Proxy cannot be cast to android.a.a.a
    at me.tatarka.support.job.JobService$JobHandler.handleMessage(Unknown Source)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5221)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
 Caused by: java.lang.ClassCastException: android.app.job.IJobCallback$Stub$Proxy cannot be cast to android.a.a.a
    at me.tatarka.support.internal.IJobServiceCompat.getCallback(Unknown Source)
    at me.tatarka.support.internal.IJobServiceCompat.access$100(Unknown Source)
    at me.tatarka.support.internal.IJobServiceCompat$3.acknowledgeStartMessage(Unknown Source)
    at me.tatarka.support.job.JobService$JobHandler.ackStartMessage(Unknown Source)
    ... 8 more
```

On Nexus 7 with Android 5.0.
Proguard rules:

```
-keep class me.tatarka.** { *; }
-dontwarn me.tatarka.**
```

**Comment by atlantis0** [comment]
Add the following line
-keep class android.app.job.IJobCallback$Stub$Proxy { *; }
